### ISSUE TITLE
Hover option quirks

### ISSUE THREAD

**Issue by murhum1** [John-Paul-R/PoE-Atlas-Website#34]
Changing the "Hover Effect" option currently requires a page reload to have an effect, as the option is only read when a [node is created](https://github.com/John-Paul-R/PoE-Atlas-Website/blob/master/js/pixi_atlas_of_worlds.js#L408).

If the hover option is disabled, the maps aren't clickable either, likely due to [`circleSprite.interactive` only being set when Hover Effect is true.](https://github.com/John-Paul-R/PoE-Atlas-Website/blob/master/js/pixi_atlas_of_worlds.js#L409) This and the accompanying `circleSprite.buttonMode` could be outside the if condition, as people will probably want to access the map sidebar even if the hover effect is disabled.

Semi-unrelated note: Should the map info sidebar be closed when an empty spot on the atlas is clicked?

**Comment by John-Paul-R** [comment]
Ah! I forgot to properly update the things this option affects when its updated. Thanks for the report!

> If the hover option is disabled, the maps aren't clickable either, likely due to [`circleSprite.interactive` only being set when Hover Effect is true.](https://github.com/John-Paul-R/PoE-Atlas-Website/blob/master/js/pixi_atlas_of_worlds.js#L409) This and the accompanying `circleSprite.buttonMode` could be outside the if condition, as people will probably want to access the map sidebar even if the hover effect is disabled.

I agree, yes.

> Semi-unrelated note: Should the map info sidebar be closed when an empty spot on the atlas is clicked?

I don't think so. At least, that's not the intended effect atm. Right now the goal is just to have it close only when the little 'x' is clicked. If people seem to want this, though, I'd add it as an option.

Ty for the help! o7

**Comment by John-Paul-R** [comment]
Fixed in df54793.
